import Link from "next/link";
import { BsFillArrowRightCircleFill } from "react-icons/bs";

export const metadata = {
	title: "Progetti",
	description: "Generated by create next app",
};

export default function ProjectDetail({ params }) {
	console.log(params);
	return (
		<main className="page">
			<h1 className="page__title">Progetto Detail: {params.slug}</h1>
			{params.description}r
			<Link className="flex items-center gap-x-3" href="/projects/">
				Go To ProjectsList
				<BsFillArrowRightCircleFill />
			</Link>
		</main>
	);
}
