export const metadata = {
    title: "About",
    description: "Generated by create next app",
};

export default function About() {
    return (
        <main className="page">
            <h1 className="page__title">About</h1>
        </main>
    )
}