import Link from "next/link";
import ProjectsList from "../../components/ProjectsList";

import { BsFillArrowRightCircleFill } from "react-icons/bs";

export const metadata = {
	title: "Projects",
	description: "Generated by create next app",
};

export default function Projects() {
	return (
		<main className="page">
			<h1 className="page__title">Projects</h1>
			<ProjectsList />
		</main>
	);
}
